In [38]:
from datasets import load_dataset

ds = load_dataset("FartLabs/FartDB")

In [39]:
print(ds)

DatasetDict({
    full: Dataset({
        features: ['Canonicalized SMILES', 'Standardized SMILES', 'Canonicalized Taste', 'Source'],
        num_rows: 15031
    })
    train: Dataset({
        features: ['Canonicalized SMILES', 'Standardized SMILES', 'Canonicalized Taste', 'Source'],
        num_rows: 10521
    })
    validation: Dataset({
        features: ['Canonicalized SMILES', 'Standardized SMILES', 'Canonicalized Taste', 'Source'],
        num_rows: 2255
    })
    test: Dataset({
        features: ['Canonicalized SMILES', 'Standardized SMILES', 'Canonicalized Taste', 'Source'],
        num_rows: 2255
    })
})

In [40]:
df = ds["full"].to_pandas()
display(df.head())

,Canonicalized SMILES,Standardized SMILES,Canonicalized Taste,Source
0,Oc1cc2c(cc1O)C1c3ccc(O)c(O)c3OCC1(O)C2,Oc1cc2c(cc1O)C1c3ccc(O)c(O)c3OCC1(O)C2,sweet,chemtastes_db
1,CC(C)=CCCC(C)(O)C1CC(O)C(C)=CC1=O,CC(C)=CCCC(C)(O)C1CC(O)C(C)=CC1=O,sweet,chemtastes_db
2,CC(=O)OC1C(=O)c2c(O)cc(O)cc2OC1c1ccc(O)c(O)c1,CC(=O)OC1C(=O)c2c(O)cc(O)cc2OC1c1ccc(O)c(O)c1,sweet,chemtastes_db
3,OC1C(O)C(O)C(O)C(O)C1O,OC1C(O)C(O)C(O)C(O)C1O,sweet,chemtastes_db
4,CON=C(C)C1CC=C(C=NO)CC1,CON=C(C)C1CC=C(C=NO)CC1,sweet,chemtastes_db

In [41]:
df.columns

Index(['Canonicalized SMILES', 'Standardized SMILES', 'Canonicalized Taste',
       'Source'],
      dtype='object')

In [42]:
df.drop(columns=[ "Source"], axis=1, inplace=True)

In [43]:
display(df.head())

,Canonicalized SMILES,Standardized SMILES,Canonicalized Taste
0,Oc1cc2c(cc1O)C1c3ccc(O)c(O)c3OCC1(O)C2,Oc1cc2c(cc1O)C1c3ccc(O)c(O)c3OCC1(O)C2,sweet
1,CC(C)=CCCC(C)(O)C1CC(O)C(C)=CC1=O,CC(C)=CCCC(C)(O)C1CC(O)C(C)=CC1=O,sweet
2,CC(=O)OC1C(=O)c2c(O)cc(O)cc2OC1c1ccc(O)c(O)c1,CC(=O)OC1C(=O)c2c(O)cc(O)cc2OC1c1ccc(O)c(O)c1,sweet
3,OC1C(O)C(O)C(O)C(O)C1O,OC1C(O)C(O)C(O)C(O)C1O,sweet
4,CON=C(C)C1CC=C(C=NO)CC1,CON=C(C)C1CC=C(C=NO)CC1,sweet

In [44]:
import pandas as pd
train_df = pd.read_csv("umami_training_dataset.csv")
test_df = pd.read_csv("Umami_testing_dataset.csv")

# Concatenate the DataFrames
umami_df = pd.concat([train_df, test_df], ignore_index=True)

In [45]:
umami_df.columns

Index(['Column1', 'SEQUENCE', 'TASTE', 'Std_SMILES', 'Parent_SMILES'], dtype='object')

In [46]:
umami_df.drop(columns=["Column1", "SEQUENCE", "Parent_SMILES"], inplace=True)

In [47]:
display(umami_df.head())

   TASTE                                         Std_SMILES
0  umami  N=C(N)NCCC[C@H](N)C(=O)N[C@@H](CCCCN)C(=O)N[C@...
1  umami  CC(C)[C@H](N)C(=O)N[C@@H](C)C(=O)N[C@H](C(=O)O...
2  umami  CC(C)C[C@H](NC(=O)[C@H](CO)NC(=O)[C@H](CCC(=O)...
3  umami  C[C@H](NC(=O)[C@@H](N)CO)C(=O)N[C@@H](CCC(=O)O...
4  umami                 CSCC[C@H](NC(=O)[C@@H](N)CS)C(=O)O

In [48]:
umami_df.rename(columns={"TASTE": "Canonicalized Taste", "Std_SMILES": "Standardized SMILES"}, inplace=True)

In [49]:
umami_df = umami_df[umami_df["Canonicalized Taste"] == "umami"].reset_index(drop=True)

In [50]:
combined_df = pd.concat([df, umami_df], ignore_index=True)

In [51]:
display(combined_df.head())

,Canonicalized SMILES,Standardized SMILES,Canonicalized Taste
0,Oc1cc2c(cc1O)C1c3ccc(O)c(O)c3OCC1(O)C2,Oc1cc2c(cc1O)C1c3ccc(O)c(O)c3OCC1(O)C2,sweet
1,CC(C)=CCCC(C)(O)C1CC(O)C(C)=CC1=O,CC(C)=CCCC(C)(O)C1CC(O)C(C)=CC1=O,sweet
2,CC(=O)OC1C(=O)c2c(O)cc(O)cc2OC1c1ccc(O)c(O)c1,CC(=O)OC1C(=O)c2c(O)cc(O)cc2OC1c1ccc(O)c(O)c1,sweet
3,OC1C(O)C(O)C(O)C(O)C1O,OC1C(O)C(O)C(O)C(O)C1O,sweet
4,CON=C(C)C1CC=C(C=NO)CC1,CON=C(C)C1CC=C(C=NO)CC1,sweet

In [52]:
combined_df["Canonicalized Taste"].value_counts()

Canonicalized Taste
sweet        9542
undefined    2150
bitter       1676
sour         1605
umami         198
Name: count, dtype: int64

In [53]:
combined_df.describe()

           Canonicalized SMILES      Standardized SMILES Canonicalized Taste
count                     15031                    15171               15171
unique                    14577                    14716                   5
top     O=C(O)c1cc(O)c(O)c(O)c1  O=C(O)c1cc(O)c(O)c(O)c1               sweet
freq                          5                        5                9542

In [54]:
combined_df = combined_df.drop_duplicates(subset="Standardized SMILES").reset_index(drop=True)
combined_df['Canonicalized Taste'].value_counts()

Canonicalized Taste
sweet        9422
undefined    2053
sour         1534
bitter       1515
umami         192
Name: count, dtype: int64

In [55]:
from rdkit import Chem

# Function to canonicalize a SMILES string
def canonicalize_smiles(smiles):
    mol = Chem.MolFromSmiles(smiles)
    if mol:
        return Chem.MolToSmiles(mol, canonical=True)
    else:
        return None

# Apply the function to the 'Standardized SMILES' column
combined_df['Canonicalized SMILES'] = combined_df['Standardized SMILES'].apply(canonicalize_smiles)

[15:31:17] WARNING: not removing hydrogen atom without neighbors
[15:31:19] WARNING: not removing hydrogen atom without neighbors
[15:31:21] WARNING: not removing hydrogen atom without neighbors
[15:31:21] WARNING: not removing hydrogen atom without neighbors
[15:31:21] WARNING: not removing hydrogen atom without neighbors

In [56]:
combined_df.to_csv("combined_deduplicated.csv", index=False)